description:
  'Just a toy tool for demoing.'
raw:
  table1:
    description: 'Table1 for tool1.'
    pattern: "\\.tool1\\.table1\\.tsv$"
    ftype: 'tsv'
    schema:
      v1.2.3:
        - field: 'SampleID'
          type: 'char'
        - field: 'Chromosome'
          type: 'char'
        - field: 'Start'
          type: 'int'
        - field: 'End'
          type: 'int'
        - field: 'metricX'
          type: 'float'
      latest:
        - field: 'SampleID'
          type: 'char'
        - field: 'Chromosome'
          type: 'char'
        - field: 'Start'
          type: 'int'
        - field: 'End'
          type: 'int'
        - field: 'metricX'
          type: 'float'
        - field: 'metricY'
          type: 'float'
        - field: 'metricZ'
          type: 'float'
  table2:
    description: 'Table2 for tool1.'
    pattern: "\\.tool1\\.table2\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'SampleID'
          type: 'char'
        - field: 'metricA'
          type: 'char'
        - field: 'metricB'
          type: 'float'
  table3:
    description: 'Table3 for tool1.'
    pattern: "\\.tool1\\.table3\\.tsv$"
    ftype: 'txt-nohead'
    schema:
      latest:
        - field: 'Variable'
          type: 'char'
        - field: 'Value'
          type: 'char'
