tidy:
  table1:
    description: 'Table1 for tool1.'
    schema:
      v1.2.3:
        tbl1:
          - field: 'sample_id'
            type: 'char'
            description: 'sample ID'
          - field: 'chromosome'
            type: 'char'
            description: 'chromosome'
          - field: 'start'
            type: 'int'
            description: 'start position'
          - field: 'end'
            type: 'int'
            description: 'end position'
          - field: 'metric_x'
            type: 'float'
            description: 'metric X'
      latest:
        tbl1:
          - field: 'sample_id'
            type: 'char'
            description: 'sample ID'
          - field: 'chromosome'
            type: 'char'
            description: 'chromosome'
          - field: 'start'
            type: 'int'
            description: 'start position'
          - field: 'end'
            type: 'int'
            description: 'end position'
          - field: 'metric_x'
            type: 'float'
            description: 'metric X'
          - field: 'metric_y'
            type: 'float'
            description: 'metric Y'
          - field: 'metric_z'
            type: 'float'
            description: 'metric Z'
  table2:
    description: 'Table2 for tool1.'
    schema:
      latest:
        tbl1:
          - field: 'sample_id'
            type: 'char'
            description: 'sample ID'
          - field: 'metric_a'
            type: 'char'
            description: 'metric A'
          - field: 'metric_b'
            type: 'float'
            description: 'metric B'
