# All available hooks: https://pre-commit.com/hooks.html
repos:
- repo: https://github.com/jolars/panache-pre-commit
  rev: v3.5.0
  hooks:
    # Format Markdown, Quarto, and RMarkdown files
    - id: panache-format
    # Lint files and auto-fix issues
    - id: panache-lint
- repo: https://github.com/posit-dev/air-pre-commit
  rev: 0.11.0
  hooks:
    - id: air-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=200']
    - id: file-contents-sorter
      files: '^\.Rbuildignore$'
    - id: check-yaml
- repo: local
  hooks:
    - id: forbid-to-commit
      name: Don't commit common R artifacts
      entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
      language: fail
      files: '\.Rhistory|\.RData|\.Rds|\.rds$'
