---
title: "Contribute"
vignette: >
  %\VignetteIndexEntry{Contribute}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---

## New Tool

Adding a new tool to a {nemo} child package consists of the following steps:

1. Data

Add subsets of data generated by the tool of interest under `inst/extdata/<tool>`.
Usually the top 10 rows (plus header) of a straightforward TSV file are fine.
[DVC] is recommended for tracking the files in version control.
See `vignette("devnotes")` for some DVC notes.

2. Configs

Use the `inst/scripts/file_to_yaml.R` script to construct the _raw_ YAML config for
the files of interest. The _tidy_ YAML configs can be prepared by copying the raw
config and tidying the field names using [snake_case]. Copilot is _fairly_ good at
constructing this when having the raw and tidy files open side by side. Pasting
tables describing the fields from the tool's official documentation can also help
Copilot with the field description.

3. Parsers

Create parsers under `R/<Tool>.R`. Use one of the other tool files as a template.

[DVC]: <https://github.com/iterative/dvc> "Data Version Control"
[snake_case]: <https://en.wikipedia.org/wiki/Snake_case> "Snake case wiki"
