---
title: "NEWS"
vignette: >
  %\VignetteIndexEntry{News}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---

```{r}
#| label: pkgs
#| message: false
#| warning: false
#| echo: false
{
  use("htmltools", "a")
  use("glue", "glue")
}
```

```{r echo=FALSE}
repo <- "https://github.com/umccr/nemo"
vdiff <- function(new, old) {
  stopifnot(utils::compareVersion(new, old) == 1)
  htmltools::a(
    href = glue::glue("{repo}/compare/v{old}...v{new}"),
    glue::glue("v{new} - v{old} diff")
  )
}

pr_or_issue <- function(n, type) {
  x <- c(iss = "issues", pr = "pull")
  stopifnot(is.numeric(n), n > 0, type %in% names(x))
  type2 <- x[type]
  htmltools::a(
    href = glue::glue("{repo}/{type2}/{n}"),
    glue::glue("{type}{n}")
  )
}

iss <- function(n) {
  pr_or_issue(n, "iss")
}

pr <- function(n) {
  pr_or_issue(n, "pr")
}
```

## DEV

## v0.0.1 (2025-09-06)

Initial release of nemo (`r pr(5)`)

- R pkg skeleton
- Documentation via pkgdown
- CLI
- Logger
- GitHub Actions CI/CD

Fixing issues `r iss(2)`, `r iss(3)` and `r iss(4)`
