# Generated by roxytest: do not edit by hand!

# File R/Workflow.R: @testexamples

test_that("Function Workflow() @ L19", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  tools <- list(tool1 = Tool1)
  wf1 <- Workflow$new(name = "foo", path = path, tools = tools)
  diro <- tempdir()
  wf1$list_files()
  wf1$nemofy(diro = diro, format = "parquet", input_id = "run1")
  (lf <- list.files(diro, pattern = "tool1.*parquet", full.names = FALSE))
  #dbconn <- DBI::dbConnect(drv = RPostgres::Postgres(), dbname = "nemo", user = "orcabus")
  #wf1$nemofy(format = "db", id = "runABC", dbconn = dbconn)
  expect_equal(length(lf), 4)
})

