# Generated by roxytest: do not edit by hand!

# File R/config_prep.R: @testexamples

test_that("Function config_prep_raw_schema() @ L25", {
  
  path <- system.file("extdata", "tool1/latest/sampleA.tool1.table1.tsv", package = "nemo")
  (x <- config_prep_raw_schema(path = path, delim = "\t"))
  expect_named(x, c("raw", "tidy", "type", "description", "versions"))
  expect_equal(nrow(x), 6L)
  expect_equal(x[1, "raw",  drop = TRUE], "SampleID")
  expect_equal(x[1, "tidy", drop = TRUE], "sample_id")
  expect_equal(x[1, "type", drop = TRUE], "char")
  expect_equal(unlist(x[[1, "versions"]]), "latest")
})


test_that("Function config_prep_raw() @ L91", {
  
  path <- system.file("extdata", "tool1/latest/sampleA.tool1.table1.tsv", package = "nemo")
  name <- "table1"
  descr <- "Table1 from Tool1."
  pat <- "\\.tool1\\.table1\\.tsv$"
  l <- config_prep_raw(path, name, descr, pat)
  expect_equal(names(l[[1]]), c("description", "pattern", "ftype", "columns"))
  expect_equal(length(l[[1]][["columns"]]), 6L)
  col1 <- l[[1]][["columns"]][[1]]
  expect_named(col1, c("raw", "tidy", "type", "description", "versions"))
  expect_equal(col1[["raw"]], "SampleID")
  expect_equal(col1[["tidy"]], "sample_id")
})


test_that("Function config_prep_multi() @ L125", {
  
  dir1 <-  "extdata/tool1/latest"
  path1 <- system.file(dir1, "sampleA.tool1.table1.tsv", package = "nemo")
  path2 <- system.file(dir1, "sampleA.tool1.table2.tsv", package = "nemo")
  x <- tibble::tibble(
    name = c("table1", "table2"),
    descr = c("Table1 from Tool1.", "Table2 from Tool1."),
    pat = c("\\.tool1\\.table1\\.tsv$", "\\.tool1\\.table2\\.tsv$"),
    type = c("tsv", "tsv"),
    path = c(path1, path2)
  )
  config <- config_prep_multi(x)
  expect_equal(names(config), "tables")
  expect_equal(names(config[["tables"]]), c("table1", "table2"))
  tbl1 <- config[["tables"]][["table1"]]
  expect_equal(names(tbl1), c("description", "pattern", "ftype", "columns"))
  expect_equal(length(tbl1[["columns"]]), 6L)
  expect_named(tbl1[["columns"]][[1]], c("raw", "tidy", "type", "description", "versions"))
})


test_that("Function config_prep_write() @ L179", {
  
  dir1 <- "extdata/tool1/latest"
  path1 <- system.file(dir1, "sampleA.tool1.table1.tsv", package = "nemo")
  path2 <- system.file(dir1, "sampleA.tool1.table2.tsv", package = "nemo")
  x <- tibble::tibble(
    name = c("table1", "table2"),
    descr = c("Table1 from Tool1.", "Table2 from Tool1."),
    pat = c("\\.tool1\\.table1\\.tsv$", "\\.tool1\\.table2\\.tsv$"),
    type = c("tsv", "tsv"),
    path = c(path1, path2)
  )
  config <- config_prep_multi(x)
  out <- tempfile(fileext = ".yaml")
  config_prep_write(config, out)
  parsed <- yaml::read_yaml(out)
  expect_equal(names(parsed), "tables")
  expect_equal(names(parsed[["tables"]]), c("table1", "table2"))
  tbl1 <- parsed[["tables"]][["table1"]]
  expect_equal(names(tbl1), c("description", "pattern", "ftype", "columns"))
  col1 <- tbl1[["columns"]][[1]]
  expect_named(col1, c("raw", "tidy", "type", "description", "versions"))
  expect_equal(col1[["raw"]], "SampleID")
  expect_equal(col1[["versions"]][[1]], "latest")
})

