# Generated by roxytest: do not edit by hand!

# File R/Tool1.R: @testexamples

test_that("Function Tool1() @ L16", {
  
  cls <- Tool1
  indir <- system.file("extdata/tool1", package = "nemo")
  odir <- tempdir()
  id <- "tool1_run1"
  obj <- cls$new(indir)
  obj$nemofy(diro = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "tool1.*parquet", full.names = FALSE))
  expect_equal(length(lf), 4)
})

