# Generated by roxytest: do not edit by hand!

# File R/Workflow1.R: @testexamples

test_that("Function Workflow1() @ L15", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  odir <- tempdir()
  id <- "workflow1_run1"
  w <- Workflow1$new(path)
  x <- w$nemofy(odir = odir, format = "parquet", id = id)
  (lf <- list.files(odir, pattern = "tool1.*parquet", full.names = FALSE))
  expect_equal(length(lf), 4)
})

