# Generated by roxytest: do not edit by hand!

# File R/parse.R: @testexamples

test_that("Function parse_file() @ L26", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  x <- Tool$new("tool1", pkg = "nemo", path)
  schemas_all <- x$raw_schemas_all
  pname <- "table1"
  fpath <- file.path(path, "latest", "sampleA.tool1.table1.tsv")
  (d <- parse_file(fpath, pname, schemas_all))
  
  expect_equal(names(d)[1:3], c("SampleID", "Chromosome", "Start"))
})


test_that("Function parse_file_nohead() @ L70", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  x <- Tool$new("tool1", pkg = "nemo", path = path)
  schema <- x$raw_schemas_all |>
         dplyr::filter(.data$name == "table3") |>
         dplyr::select("version", "schema")
  fpath <- file.path(path, "latest", "sampleA.tool1.table3.tsv")
  (d <- parse_file_nohead(fpath, schema))
  
  expect_equal(names(d), c("Variable", "Value"))
})


test_that("Function file_hdr() @ L114", {
  
  dir1 <- system.file("extdata/tool1", package = "nemo")
  fpath <- file.path(dir1, "latest", "sampleA.tool1.table1.tsv")
  (hdr <- file_hdr(fpath))
  
  expect_equal(hdr[1:2], c("SampleID", "Chromosome"))
})


test_that("Function schema_guess() @ L154", {
  
  dir1 <- system.file("extdata/tool1", package = "nemo")
  fpath1 <- file.path(dir1, "latest", "sampleA.tool1.table1.tsv")
  fpath2 <- file.path(dir1, "v1.2.3", "sampleA.tool1.table1.tsv")
  pname <- "table1"
  cnames1 <- file_hdr(fpath1)
  cnames2 <- file_hdr(fpath2)
  conf <- Config$new("tool1", pkg = "nemo")
  schemas_all <- conf$get_raw_schemas_all()
  (s1 <- schema_guess(pname, cnames1, schemas_all))
  (s2 <- schema_guess(pname, cnames2, schemas_all))
  
  expect_equal(length(s1), 2)
  expect_equal(s1[["version"]], "latest")
  expect_equal(s2[["version"]], "v1.2.3")
})

