# Generated by roxytest: do not edit by hand!

# File R/utils.R: @testexamples

test_that("Function list_files_dir() @ L20", {
  
  d <- system.file("R", package = "nemo")
  x <- list_files_dir(d)
  expect_equal(names(x), c("bname", "size", "lastmodified", "path"))
})


test_that("Function get_tbl_version_attr() @ L53", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  path2 <- file.path(path, "v1.2.3", "sampleA.tool1.table1.tsv")
  x <- Tool1$new(path)$tidy(keep_raw = TRUE)
  ind <- which(x$tbls$path == path2)
  stopifnot(length(ind) == 1)
  (v <- get_tbl_version_attr(x$tbls$raw[[ind]]))
  
  expect_equal(v, "v1.2.3")
})


test_that("Function set_tbl_version_attr() @ L79", {
  
  d <- tibble::tibble(a = 1:3, b = letters[1:3])
  v <- "v1.2.3"
  d <- set_tbl_version_attr(d, v)
  (a <- attr(d, "file_version"))
  
  expect_equal(a, v)
})


test_that("Function empty_tbl() @ L100", {
  
  (x <- empty_tbl(cnames = c("a", "b", "c")))
  expect_equal(nrow(x), 0)
})


test_that("Function nemoverse_wf_dispatch() @ L152", {
  
  wf <- "basemean"
  (x <- nemoverse_wf_dispatch(wf))
  expect_equal(x, base::mean)
})

