# Generated by roxytest: do not edit by hand!

# File R/Config.R: @testexamples

test_that("Function Config() @ L28", {
  
  tool <- "tool1"
  pkg <- "nemo"
  conf <- Config$new(tool, pkg)
  conf$get_raw_patterns()
  (rv1 <- conf$get_raw_versions())
  conf$get_raw_descriptions()
  conf$get_raw_schemas_all()
  conf$get_raw_schema("table1")
  conf$get_raw_schema("table1", v = "v1.2.3")
  conf$are_raw_schemas_valid()
  conf$get_tidy_descriptions()
  (ts1 <- conf$get_tidy_schemas_all())
  conf$get_tidy_schema("table1")
  conf$get_tidy_schema("table1", v = "v1.2.3")
  
  expect_true(conf$are_raw_schemas_valid())
  expect_true(ts1 |> dplyr::filter(.data$name == "table1") |> nrow() == 2)
  expect_true(all(unique(rv1$value) == c("v1.2.3", "latest")))
  expect_error(Config$new("foo", pkg))
})

